### ISSUE TITLE
Force close on android oreo

### ISSUE THREAD

**Issue by sajorahasan** [broakenmedia/MultiContactPicker#5]
`FATAL EXCEPTION: main
                                                                          Process: com.sajorahasan.eventify, PID: 19170
                                                                          java.lang.NoSuchFieldError: No static field action_search of type I in class Lcom/wafflecopter/multicontactpicker/R$id; or its superclasses (declaration of 'com.wafflecopter.multicontactpicker.R$id' appears in /data/app/com.sajorahasan.eventify-zvpFl1zeiv66euaVibwe5Q==/split_lib_slice_8_apk.apk)
                                                                              at com.wafflecopter.multicontactpicker.MultiContactPickerActivity.onCreateOptionsMenu(MultiContactPickerActivity.java:166)`

**Comment by broakenmedia** [comment]
I'm not sure what to suggest on that one i'm afraid, "action_search" is just a menu item ID, there should be no difference between OS versions

**Comment by broakenmedia** [comment]
OK, i also just tested this on an Android O device and have no crash. Can you give me some more detail on what you're doing?

**Comment by sajorahasan** [comment]
Hi, I'm using Android Studio 3 beta 6 and I'm testing the app on physical device running android 8.0.0 and my targetSdkVersion  is 26.
whenever i click on button to start contact picker activity it force close with these logs.
` --------- beginning of crash
09-29 08:40:50.410 13654-13654/com.sajorahasan.eventify E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.sajorahasan.eventify, PID: 13654
                                                                          java.lang.NoSuchFieldError: No static field action_search of type I in class Lcom/wafflecopter/multicontactpicker/R$id; or its superclasses (declaration of 'com.wafflecopter.multicontactpicker.R$id' appears in /data/app/com.sajorahasan.eventify-g-iPSXDLexusiCOl3QpNYg==/split_lib_slice_8_apk.apk)
                                                                              at com.wafflecopter.multicontactpicker.MultiContactPickerActivity.onCreateOptionsMenu(MultiContactPickerActivity.java:166)
                                                                              at android.app.Activity.onCreatePanelMenu(Activity.java:3418)
                                                                              at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:328)
                                                                              at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:93)
                                                                              at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:332)
                                                                              at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:93)
                                                                              at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
                                                                              at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
                                                                              at android.os.Handler.handleCallback(Handler.java:789)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                              at android.os.Looper.loop(Looper.java:164)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by broakenmedia** [comment]
It's not something as simple as your context being null/for the wrong activity is it? I've just setup a new fragment in O and again having no issue, can you swap out the context for a straight up "getActivity()"?

**Comment by broakenmedia** [comment]
I've just updated the lib to 1.5. Can you please update your build.gradle and let me know if that resolves the issue?

**Comment by sajorahasan** [comment]
No, It was issue with menu file name "menu_main.xml", simply renaming menu file name resolve the issue.
Thank you for the help

**Comment by broakenmedia** [comment]
Brilliant, thanks for the update, I’ll also rename the menu file to something more unique in the next release!

Sent from phone

On 30 Sep 2017, at 2:16 am, Hasan Sajora <notifications@github.com<mailto:notifications@github.com>> wrote:


No, It was issue with menu file name "menu_main.xml", simply renaming menu file name resolve the issue.
Thank you for the help
