### ISSUE TITLE
Dos not work with 'com.android.support:appcompat-v7:26.+'

### ISSUE THREAD

**Issue by shimiuh** [broakenmedia/MultiContactPicker#6]
this is the error 

10-24 07:57:14.809 710-710/app.craze.screenshop E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: app.craze.screenshop, PID: 710
                                                                  java.lang.NoSuchFieldError: No static field mcp_action_search of type I in class Lcom/wafflecopter/multicontactpicker/R$id; or its superclasses (declaration of 'com.wafflecopter.multicontactpicker.R$id' appears in /data/app/app.craze.screenshop-2/split_lib_slice_5_apk.apk)
                                                                      at com.wafflecopter.multicontactpicker.MultiContactPickerActivity.onCreateOptionsMenu(MultiContactPickerActivity.java:166)
                                                                      at android.app.Activity.onCreatePanelMenu(Activity.java:2823)
                                                                      at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:320)
                                                                      at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:95)
                                                                      at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:333)
                                                                      at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:95)
                                                                      at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:454)
                                                                      at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by broakenmedia** [comment]
I believe a temporary fix is to rename your menu file. Is it currently name "menu_main.xml"? If so, change the name and recompile and it should work. I will rename the menu file in the library shortly and release a new version which will remove the need to do this when i can.

**Comment by shimiuh** [comment]
thanks this is working now
